#!/bin/sh

### BEGIN INIT INFO
# Provides:          actuator
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Smac Actuator
# Description:       Smac Actuator verifica lo stato di funzionamento del sistema. In base alle temperature rilevate
#                    e al programma impostato calcola lo stato in cui il relè di controllo della caldaia si dovrebbe
#                    trovare, quindi invia il comando di impostazione di stato allo swither tramite la pipe gestita
#                    dal communicator.
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/opt/smac/bin
DAEMON=$DIR/actuator.py
DAEMON_NAME=actuator

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=pi

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME/$DAEMON_NAME.pid

# Daemon Log file
LOGFILE=/opt/smac/log/$DAEMON_NAME.log

# Add any command line options for your daemon here
DAEMON_OPTS="--pid $PIDFILE --log $LOGFILE"

. /lib/lsb/init-functions

mkdir -p /var/run/$DAEMON_NAME
chown -R $DAEMON_USER /var/run/$DAEMON_NAME

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --pidfile $PIDFILE --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS start
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10 --startas $DAEMON -- $DAEMON_OPTS stop
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc -p "$PIDFILE" "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
